Repository ibexa/system-info, pull requests merged in 2021-11, with the labels that each got.

#3 Merge up of ezsystems/ez-support-tools#110
  .github/workflows/pr-check.yaml
Labels: Ready for review

#5 IBX-1466: Switched to \Ibexa\Contracts\Core\Ibexa::VERSION
  src/bundle/DependencyInjection/IbexaSystemInfoExtension.php
  src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
  tests/bundle/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php
Labels: Feature, Ready for review

#4 IBX-1396: Exposed services used within the project
  composer.json
  src/bundle/DependencyInjection/IbexaSystemInfoExtension.php
  src/bundle/Resources/config/default_settings.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/translations/systeminfo.en.xliff
  src/bundle/Resources/views/themes/admin/system_info/services.html.twig
  src/bundle/SystemInfo/Collector/ServicesSystemInfoCollector.php
  src/bundle/SystemInfo/Exception/SystemInfoServiceNotFoundException.php
  src/bundle/SystemInfo/Value/ServicesSystemInfo.php
  src/lib/Service/AggregateServiceProvider.php
  src/lib/Service/HttpCacheServiceInfo.php
  src/lib/Service/PersistenceCacheServiceInfo.php
  src/lib/Service/SearchEngineServiceInfo.php
  src/lib/Service/ServiceInfo.php
  src/lib/Service/ServiceProviderInterface.php
  tests/bundle/DependencyInjection/IbexaSystemInfoExtensionTest.php
  tests/bundle/SystemInfo/Collector/ServicesSystemInfoCollectorTest.php
Labels: Feature, QA approved
