Repository ibexa/system-info, pull requests merged in 2025-05, with the labels that each got.

#66 IBX-8471: Upgraded codebase to Symfony 7
  composer.json
  phpstan.neon
  src/bundle/SystemInfo/Collector/RepositorySystemInfoCollector.php
  src/lib/Storage/Metrics/ContentTypesCountMetrics.php
  src/lib/Storage/Metrics/DraftsCountMetrics.php
  src/lib/Storage/Metrics/PublishedContentObjectsCountMetrics.php
  src/lib/Storage/Metrics/UsersCountMetrics.php
  src/lib/Storage/Metrics/VersionsCountMetrics.php
  tests/bundle/SystemInfo/Collector/RepositorySystemInfoCollectorTest.php
Labels: Ready for SF7

#68 IBX-9697: Refactored components to align with new twig-components package
  composer.json
  src/bundle/Resources/config/systeminfo.yaml
  src/bundle/Resources/views/themes/admin/system_info/info.html.twig
  src/lib/Component/Dashboard/EzInfoTwigComponent.php
  tests/integration/Kernel.php
Labels: QA approved

#72 IBX-9940: Removed Sass deprecations
  src/bundle/Resources/public/scss/_system-info-helper-text.scss
  src/bundle/Resources/public/scss/system-information.scss
Labels: Ready for QA
